name: M
options:
  bundleIdPrefix: com.m
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""

targets:
  M:
    type: application
    platform: iOS
    sources:
      - path: Sources
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.m.app
        INFOPLIST_GENERATION_MODE: GeneratedFile
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"

  MUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: MUITests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: M
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.m.app.uitests
        INFOPLIST_GENERATION_MODE: GeneratedFile
        GENERATE_INFOPLIST_FILE: YES
        TEST_TARGET_NAME: M

schemes:
  M:
    build:
      targets:
        M: all
        MUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - name: MUITests
          parallelizable: false
          randomExecutionOrder: true
